a={1,2,3,4,5}
b={'a','b','c','d'}
c=a.union(b)
print(c)
a={1,2,3,4,5}
b={'a','b','c','d'}
c=a|b|c
print(c)
d={'x','y','z'}
a={1,2,3,4,5}
b={'a','b','c','d'}
c=a.union(b,d)
print(c)
x={'x','y','z'}
a={1,2,3,4,5}
b={'a','b','c','d'}
c=a|b|x
print(c)